### ISSUE TITLE
Deprecated set-output

### ISSUE THREAD

**Issue by bcdewitt** [codfish/semantic-release-action#178]
I'm getting the following warning even after bumping up to `v2`:
![image](https://user-images.githubusercontent.com/9423873/199548939-2b5812e5-8647-4f40-8e31-ecaf3833560c.png)

Here's the link in the image, in case it's helpful: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by codfish** [comment]
@bcdewitt thanks, this was fixed by https://github.com/codfish/semantic-release-action/pull/183, if you're referencing a specific sha or digest you'll need to update it! If you're just using `v2` or `main` you should be good to go.

- new sha: `uses: docker://ghcr.io/codfish/semantic-release-action@4e0079a1e7511dab622628e1bf298e572a9f3d22 `
- new docker digest: `uses: docker://ghcr.io/codfish/semantic-release-action@sha256:601fd6c1db9efbcfabd34ba4563e7d0b9eb0f8ba11316e3e7d6a9b6883dac8ba`
